version: "3.9"
services:
  expenditure-api:
    image: muriithike/expenditure-api-img:v1.0.0
    ports:
      - 8081:8081
    networks:
      expenditure-api-network:

networks:
  expenditure-api-network:
    driver: bridge
