spring:
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  generate-ddl: true
datasource:
  url: ${DATABASE_URL:jdbc:h2:mem:finportal}
  username: ${DATABASE_USERNAME:sa}
  password: ${DATABASE_PASSWORD:password}
server:
  error:
    include-messages: always
  port: 8081
  servlet:
    context-path: /api/v1