spring:
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  generate-ddl: true
datasource:
  url: ${DATABASE_URL:jdbc:h2:mem:inm-campaigns}
  username: ${DATABASE_USERNAME:sa}
  password: ${DATABASE_PASSWORD:password}